import { Benefit, Category, Subscription, UserProfile, Redemption } from '@/types';

export const mockCategories: Category[] = [
  {
    id: '1',
    slug: 'saude',
    name: 'Saúde',
    description: 'Exames, consultas e procedimentos médicos com desconto',
    icon: '🏥',
    color: 'bg-green-100 text-green-700',
    benefitCount: 156,
    featured: true,
  },
  {
    id: '2',
    slug: 'seguros',
    name: 'Seguros',
    description: 'Seguros de vida, auto e residencial com condições especiais',
    icon: '🛡️',
    color: 'bg-blue-100 text-blue-700',
    benefitCount: 45,
    featured: true,
  },
  {
    id: '3',
    slug: 'bem-estar',
    name: 'Bem-estar',
    description: 'Academias, spas e tratamentos estéticos',
    icon: '💆',
    color: 'bg-purple-100 text-purple-700',
    benefitCount: 89,
    featured: true,
  },
  {
    id: '4',
    slug: 'lazer',
    name: 'Lazer',
    description: 'Cinema, teatro, restaurantes e entretenimento',
    icon: '🎭',
    color: 'bg-orange-100 text-orange-700',
    benefitCount: 234,
    featured: false,
  },
  {
    id: '5',
    slug: 'educacao',
    name: 'Educação',
    description: 'Cursos, idiomas e capacitação profissional',
    icon: '📚',
    color: 'bg-indigo-100 text-indigo-700',
    benefitCount: 67,
    featured: false,
  },
  {
    id: '6',
    slug: 'tecnologia',
    name: 'Tecnologia',
    description: 'Software, hardware e serviços digitais',
    icon: '💻',
    color: 'bg-gray-100 text-gray-700',
    benefitCount: 34,
    featured: false,
  },
];

export const mockBenefits: Benefit[] = [
  {
    id: '1',
    slug: 'exame-admissional-completo',
    name: 'Exame Admissional Completo',
    category: 'saude',
    partnerName: 'Clínica Ravim Centro',
    partnerLogo: 'https://images.pexels.com/photos/4226140/pexels-photo-4226140.jpeg?auto=compress&cs=tinysrgb&w=400',
    shortDescription: 'Exame médico ocupacional completo para admissão',
    fullDescription: 'Exame médico ocupacional completo incluindo avaliação clínica, exames complementares, audiometria, acuidade visual, eletrocardiograma e todos os procedimentos necessários para admissão conforme NR-7.',
    rules: 'Válido para agendamento até 30 dias após o resgate. Não cumulativo com outras promoções. Necessário apresentar documento com foto.',
    discountLabel: '40% OFF',
    discountPercentage: 40,
    originalPrice: 150.00,
    discountedPrice: 89.90,
    city: 'São Paulo',
    state: 'SP',
    address: 'Av. Paulista, 1000 - Bela Vista',
    phone: '(11) 3333-4444',
    website: 'https://ravimcentro.com.br',
    featured: true,
    active: true,
    validUntil: '2024-12-31',
    image: 'https://images.pexels.com/photos/4226140/pexels-photo-4226140.jpeg?auto=compress&cs=tinysrgb&w=800',
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    slug: 'seguro-vida-individual',
    name: 'Seguro Vida Individual',
    category: 'seguros',
    partnerName: 'Seguradora Vida+',
    partnerLogo: 'https://images.pexels.com/photos/4386321/pexels-photo-4386321.jpeg?auto=compress&cs=tinysrgb&w=400',
    shortDescription: 'Proteção completa para você e sua família',
    fullDescription: 'Seguro de vida individual com cobertura de até R$ 100.000 para morte natural ou acidental, invalidez permanente total ou parcial, e assistência funeral. Ideal para quem busca proteção financeira para a família.',
    rules: 'Desconto válido apenas para novos clientes. Carência de 24 meses para morte natural. Suicídio coberto após 2 anos de vigência.',
    discountLabel: '25% OFF',
    discountPercentage: 25,
    originalPrice: 89.90,
    discountedPrice: 67.43,
    featured: false,
    active: true,
    image: 'https://images.pexels.com/photos/4386321/pexels-photo-4386321.jpeg?auto=compress&cs=tinysrgb&w=800',
    createdAt: '2024-01-02T00:00:00Z',
  },
  {
    id: '3',
    slug: 'academia-premium',
    name: 'Academia Premium',
    category: 'bem-estar',
    partnerName: 'FitLife Academia',
    partnerLogo: 'https://images.pexels.com/photos/1552242/pexels-photo-1552242.jpeg?auto=compress&cs=tinysrgb&w=400',
    shortDescription: 'Acesso completo à academia com personal trainer',
    fullDescription: 'Mensalidade completa da academia incluindo musculação, aulas coletivas, piscina, sauna e 2 sessões mensais com personal trainer. Equipamentos modernos e ambiente climatizado.',
    rules: 'Válido para planos anuais. Fidelidade mínima de 12 meses. Taxa de matrícula inclusa no primeiro mês.',
    discountLabel: 'Primeira mensalidade grátis',
    discountPercentage: 0,
    city: 'São Paulo',
    state: 'SP',
    address: 'Rua Augusta, 500 - Consolação',
    phone: '(11) 2222-3333',
    featured: true,
    active: true,
    image: 'https://images.pexels.com/photos/1552242/pexels-photo-1552242.jpeg?auto=compress&cs=tinysrgb&w=800',
    createdAt: '2024-01-03T00:00:00Z',
  },
  {
    id: '4',
    slug: 'consulta-cardiologica',
    name: 'Consulta Cardiológica',
    category: 'saude',
    partnerName: 'CardioClínica',
    partnerLogo: 'https://images.pexels.com/photos/4226219/pexels-photo-4226219.jpeg?auto=compress&cs=tinysrgb&w=400',
    shortDescription: 'Consulta completa com cardiologista experiente',
    fullDescription: 'Consulta cardiológica completa incluindo anamnese detalhada, exame físico, eletrocardiograma de repouso e orientações preventivas. Médico especialista com mais de 15 anos de experiência.',
    rules: 'Agendamento com 48h de antecedência. Válido por 60 dias após o resgate. Inclui ECG.',
    discountLabel: 'R$ 100 OFF',
    discountPercentage: 33,
    originalPrice: 300.00,
    discountedPrice: 200.00,
    city: 'Rio de Janeiro',
    state: 'RJ',
    address: 'Av. Copacabana, 200 - Copacabana',
    phone: '(21) 3333-4444',
    featured: false,
    active: true,
    image: 'https://images.pexels.com/photos/4226219/pexels-photo-4226219.jpeg?auto=compress&cs=tinysrgb&w=800',
    createdAt: '2024-01-04T00:00:00Z',
  },
  {
    id: '5',
    slug: 'cinema-premium',
    name: 'Cinema Premium',
    category: 'lazer',
    partnerName: 'CineMax',
    partnerLogo: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400',
    shortDescription: 'Ingressos com desconto para os principais cinemas',
    fullDescription: 'Ingressos para salas convencionais e premium em toda a rede CineMax. Válido para todos os filmes em cartaz, exceto estreias e sessões especiais.',
    rules: 'Válido de segunda a quinta-feira. Não válido para estreias e pré-estreias. Máximo 4 ingressos por resgate.',
    discountLabel: '30% OFF',
    discountPercentage: 30,
    originalPrice: 25.00,
    discountedPrice: 17.50,
    featured: false,
    active: true,
    image: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=800',
    createdAt: '2024-01-05T00:00:00Z',
  },
  {
    id: '6',
    slug: 'curso-ingles-online',
    name: 'Curso Online de Inglês',
    category: 'educacao',
    partnerName: 'EnglishPro',
    partnerLogo: 'https://images.pexels.com/photos/4144923/pexels-photo-4144923.jpeg?auto=compress&cs=tinysrgb&w=400',
    shortDescription: 'Acesso completo à plataforma de ensino de inglês',
    fullDescription: 'Curso completo de inglês online com metodologia exclusiva, aulas ao vivo, exercícios interativos, certificado reconhecido e suporte pedagógico 24h.',
    rules: 'Acesso por 12 meses. Certificado incluso mediante aprovação. Suporte técnico e pedagógico incluído.',
    discountLabel: '50% OFF',
    discountPercentage: 50,
    originalPrice: 199.90,
    discountedPrice: 99.95,
    featured: true,
    active: true,
    image: 'https://images.pexels.com/photos/4144923/pexels-photo-4144923.jpeg?auto=compress&cs=tinysrgb&w=800',
    createdAt: '2024-01-06T00:00:00Z',
  },
];

export const mockSubscriptions: Subscription[] = [
  {
    id: 'monthly',
    plan: 'monthly',
    name: 'Plano Mensal',
    price: 14.90,
    features: [
      'Acesso a todos os benefícios',
      'Descontos exclusivos',
      'Suporte prioritário',
      'Notificações personalizadas',
      'Histórico completo',
      'Tokens de segurança',
    ],
  },
  {
    id: 'yearly',
    plan: 'yearly',
    name: 'Plano Anual',
    price: 149.90,
    originalPrice: 178.80,
    features: [
      'Acesso a todos os benefícios',
      'Descontos exclusivos',
      'Suporte prioritário',
      'Notificações personalizadas',
      'Histórico completo',
      'Tokens de segurança',
      '2 meses grátis',
      'Benefícios premium exclusivos',
      'Desconto adicional em parceiros',
    ],
    popular: true,
    savings: 'Economize R$ 28,90',
  },
];

export const mockUser: UserProfile = {
  id: '1',
  name: 'João Silva Santos',
  cpf: '123.456.789-00',
  email: 'joao.silva@email.com',
  phone: '(11) 99999-9999',
  subscriptionStatus: 'active',
  plan: 'monthly',
  planStartDate: '2024-01-01T00:00:00Z',
  planEndDate: '2024-02-01T00:00:00Z',
  paymentMethod: 'card',
  createdAt: '2024-01-01T00:00:00Z',
  preferences: {
    webPush: true,
    marketing: true,
    dataSharing: false,
  },
};

export const mockRedemptions: Redemption[] = [
  {
    id: '1',
    token: 'ABC123DEF456',
    benefitId: '1',
    benefitName: 'Exame Admissional Completo',
    partnerName: 'Clínica Ravim Centro',
    status: 'used',
    createdAt: '2024-01-15T14:30:00Z',
    expiresAt: '2024-01-15T18:30:00Z',
    usedAt: '2024-01-15T15:45:00Z',
    qrCode: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==',
    instructions: 'Apresente este token na recepção da clínica junto com um documento com foto.',
    value: 89.90,
  },
  {
    id: '2',
    token: 'XYZ789GHI012',
    benefitId: '3',
    benefitName: 'Academia Premium',
    partnerName: 'FitLife Academia',
    status: 'used',
    createdAt: '2024-01-10T09:00:00Z',
    expiresAt: '2024-01-10T21:00:00Z',
    usedAt: '2024-01-10T10:30:00Z',
    qrCode: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==',
    instructions: 'Apresente este token na recepção da academia para ativação da matrícula.',
  },
  {
    id: '3',
    token: 'DEF456ABC789',
    benefitId: '5',
    benefitName: 'Cinema Premium',
    partnerName: 'CineMax',
    status: 'generated',
    createdAt: '2024-01-20T19:30:00Z',
    expiresAt: '2024-01-21T23:59:00Z',
    qrCode: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==',
    instructions: 'Apresente este token na bilheteria do cinema para retirar os ingressos.',
    value: 17.50,
  },
];